In [17]:
"""
Program Name: Iris Flower Classifier
Date: 24/06/2018
Author: Hasnain Cheena
Description: Iris Flower Classifier using various classification algorithms.
             Algorithms used: Decision Tree, K-Nearest Neighbours and Logistic Regression

"""

'\nProgram Name: Iris Flower Classifier\nDate: 24/06/2018\nAuthor: Hasnain Cheena\nDescription: Iris Flower Classifier using various classification algorithms.\n             Algorithms used: Decision Tree, K-Nearest Neighbours and Logistic Regression\n\n'

In [18]:
from sklearn import tree, neighbors
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
import random
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split  
from sklearn.metrics import classification_report, confusion_matrix 

In [19]:
#import iris dataset
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header = None, 
                  names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
#note: target names are the labels and the features are the actual data

In [20]:
#split into features and labels
data = iris.drop('species', axis = 1)
labels = iris['species']
#split into training and testing datasets
train, test, train_labels, test_labels = train_test_split(data, labels, test_size = 0.20) 

In [21]:
#predict species of flower depending on the sepal length, sepal width, petal length & petal width
#create decision tree classifier
t_clf = tree.DecisionTreeClassifier()
t_clf.fit(train, train_labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
#predictions 
output_t = t_clf.predict(test) #prediction using decision tree

In [23]:
print(confusion_matrix(test_labels, output_t))

[[10  0  0]
 [ 0  5  0]
 [ 0  1 14]]


In [24]:
print(classification_report(test_labels, output_t))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.83      1.00      0.91         5
 Iris-virginica       1.00      0.93      0.97        15

    avg / total       0.97      0.97      0.97        30



In [25]:
#use K-Nearest Neighbours classifier 
k_clf = neighbors.KNeighborsClassifier()
k_clf.fit(train, train_labels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [26]:
output_KNN = k_clf.predict(test) #prediction using KNN 

In [27]:
print(confusion_matrix(test_labels, output_KNN))

[[10  0  0]
 [ 0  5  0]
 [ 0  0 15]]


In [28]:
print(classification_report(test_labels, output_KNN))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         5
 Iris-virginica       1.00      1.00      1.00        15

    avg / total       1.00      1.00      1.00        30



In [29]:
#use logistic regression as a classifier
model = LogisticRegression()
l_clf = model.fit(train, train_labels)

In [30]:
output_LR = l_clf.predict(test) #prediction using KNN 

In [31]:
print(confusion_matrix(test_labels, output_LR))

[[10  0  0]
 [ 0  4  1]
 [ 0  0 15]]


In [32]:
print(classification_report(test_labels, output_LR))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.80      0.89         5
 Iris-virginica       0.94      1.00      0.97        15

    avg / total       0.97      0.97      0.97        30

